name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: docker/login-action@v1
    - name: Login to DockerHub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sample-webapp:$(date +%s)

    - name: Build and push
    - uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: siddy555/app:latest
